name: GitHub Snake Game 🐍

on:
  # Run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

  # Allow manual workflow triggers
  workflow_dispatch:

  # Run on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate snake animation
      - name: Generate GitHub Contributions Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SpicychieF05
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-ocean.gif?color_snake=#FFA500&color_dots=#c6e48b,#7bc96f,#239a3b,#196127,#003300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy generated snake to output branch
      - name: Deploy Snake Animation to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update GitHub contribution snake animation 🐍 [skip ci]"
